QT_OSX_PATH = ../../Qt5.7.0/5.7/clang_64/bin

dmg:
	rm -rf compdb.dmg compdb.app
	make clean
	qmake -config release
	make -j4
	$(QT_OSX_PATH)/macdeployqt compdb.app -dmg -verbose=3

dmg-debug:
	rm -rf compdb.dmg compdb.app
	make clean
	qmake -config debug
	make -j4
	$(QT_OSX_PATH)/macdeployqt compdb.app -dmg -verbose=3 -no-strip
